version: "3.9"
services:
    redis:
       image: 'redis:alpine'
       ports:
            - '6379:6379'
    managerfrontend:
        build:
            context: ./managerfrontend
        ports:
            - '80:80'
    managerbackend:
        build:
            context: ./managerbackend
        ports:
            - "8000:8000"
        container_name: managerbackend
        depends_on:
            - managerfrontend
    
