version: "3.9"
services:
    redis:
       image: 'redis:alpine'
       ports:
            - '6379:6379'
    managerbackend:
        build:
            context: ./managerBackend
        ports:
            - "5000:5000"
    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
        depends_on:
            - managerbackend
            - redis
