version: "3.9"
services:
    redis:
       image: 'redis:alpine'
       ports:
            - '6379:6379'
    managerbackend:
        build:
            context: ./managerbackend
        ports:
            - "5000:5000"
    managerfrontend:
        build:
            context: ./managerfrontend
        ports:
            - '80:80'
